apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      containers:
        - name: application-container
          image: application-image
          resources:
            limits:
              memory: 2Gi
              cpu: 2000m
            requests:
              memory: 2Gi
              cpu: 1000m