apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./all.yaml

namePrefix: sample-x-

commonLabels:
  application: sample-x

images:
- name: application-image
  newName: abkura/jboss-profiler
  newTag: latest

patches:
- path: patches/env-patch.yaml
  target:
    kind: Deployment
      
- path: resources/deployment.yaml
  target:
    kind: Deployment
    
- path: resources/resource-limits.yaml
  target:
    kind: Deployment
